topics:
  # Perception topics
  - /nw/perception/front_camera/left/image_compressed
  - /zed/front_camera/left/camera_info
  - /nw/perception/front_camera/right/image_compressed
  - /zed/front_camera/right/camera_info
  - /zed/front_camera/depth/depth_registered
  - /zed/front_camera/depth/depth_registered/camera_info
  # Topics from PX4
  - /fmu/out/battery_status
  - /fmu/out/estimator_status_flags
  - /fmu/out/manual_control_setpoint
  - /fmu/out/position_setpoint_triplet
  - /fmu/out/sensor_combined
  - /fmu/out/vehicle_attitude
  - /fmu/out/vehicle_global_position
  - /fmu/out/vehicle_gps_position
  - /fmu/out/vehicle/_local_position
  - /fmu/out/vehicle_odometry
  - /fmu/out/vehicle_status
  - /fmu/out/vehicle_trajectory_waypoint_desired